source 'https://rubygems.org'
ruby '2.3.1'

gem 'puma'
gem 'rails', '~> 4.2.1'
gem 'sass-rails', '~> 5.0'
gem 'react-rails'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'

gem 'devise'
gem 'cancancan'
gem 'bootstrap-sass'

group :production do
  gem 'pg'
  gem 'rails_12factor'
end

group :development, :test do
  gem 'sqlite3'
  gem 'byebug'
  gem 'spring'
end
